# Generated by Django 3.1 on 2020-08-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vid',
            new_name='hall',
        ),
    ]
